const colors = {
    "P": "transparent",
    "M": "#800080",
    "Y": "#f7a01fff",
    "W": "#ffffff",
    "N": "#000000",
};

const purpleMan = [
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPMMMMMMPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPMMMMMMMMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPMMMMMMMMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPMMMMMMMMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPWMMMWMMMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPWNNMWNNMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPMMMMMMMMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPNNNNNNNMPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPMNNNNNMMMPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPNNNNNMMMMPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPMMMMMMPMMPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPMMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPMMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPYYYMMMMPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPYYMMMMMPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPMYYMMMMMPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMPPPPP",
"PPMMMPPPPPMMMPPPPPPMMMMMMMMMMMMPPPPP",
"PPPMMMPPPMMMPPPPPMMMMMMMMMMMMMMPPPPP",
"PPPPPMMMMMMMMMMMMMMMMMPPMMMMMMMPPPPP",
"PPPPPPPMMMPMMMMMMMMPPPPPMMMMMMMPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPMMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPMMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPMMMMMMMPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPMMMMMMMPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
];

//Aniamcion cuadro a cuadro 

async function createPixelArtSlow(matrix){
    const container = document.getElementById("pixelArt");
    container.innerHTML = ""; // Limpiar el contenedor antes de agregar nuevos cuadros

    for( let row = 0; row < matrix.length; row++){
        for (let col = 0; col < matrix[row].length; col++) {
            const pixel = matrix[row][col];

            const cell = document.createElement("div");
            cell.style.width = "16px";
            cell.style.height = "16px";
            cell.style.background = colors[pixel];

            container.appendChild(cell);

            await new Promise(resolve => setTimeout(resolve,20));  
        }
    }
}

document.getElementById("startBtn").addEventListener("click", () => {
    //cambiar fondo
    document.body.classList.add("grid-background");

    //Quitar boton
    document.getElementById("startBtn").style.display = "none";

    //Mostrar pixel art
    const art = document.getElementById("pixelArt");
    art.style.display = "grid";

    //Dibujar pixel art
    createPixelArtSlow(purpleMan);
})